spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 10240MB

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.gl: debug

fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
    - 192.168.1.222:22122
    - 192.168.1.223:22122



